spring:
  application:
    name: module-inventory

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inventorydb
    name: finpulse
    password: finpulse

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


server:
  port: 8082
